# Docker Compose override for development
# This file extends docker-compose.yml for local development
version: "3.9"

services:
  # Override API services for development with local build and volume mounts
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    image: course-registration-api:dev
    volumes:
      - .:/app/src:ro # Mount source for development (read-only)
    environment:
      - CONFIG_ENV=development
      - GIN_MODE=debug
    ports:
      - "8081:8080" # Expose for direct access during development

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    image: course-registration-api:dev
    volumes:
      - .:/app/src:ro
    environment:
      - CONFIG_ENV=development
      - GIN_MODE=debug
    ports:
      - "8082:8080"

  api3:
    build:
      context: .
      dockerfile: Dockerfile
    image: course-registration-api:dev
    volumes:
      - .:/app/src:ro
    environment:
      - CONFIG_ENV=development
      - GIN_MODE=debug
    ports:
      - "8083:8080"

  api4:
    build:
      context: .
      dockerfile: Dockerfile
    image: course-registration-api:dev
    volumes:
      - .:/app/src:ro
    environment:
      - CONFIG_ENV=development
      - GIN_MODE=debug
    ports:
      - "8084:8080"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=pgbouncer:6432
    networks: [app-network]
    depends_on:
      - pgbouncer

networks:
  app-network:
    external: true
