app:
  name: "course-registration-system"
  version: "1.0.0"
  environment: "docker"
  description: "University Course Registration System"

server:
  host: "0.0.0.0"
  port: "8080"
  read_timeout: 30
  write_timeout: 30
  max_header_bytes: 1048576

database:
  driver: "postgres"
  host: "postgres" # docker-compose service name
  port: 5432
  username: "postgres"
  password: "password123"
  name: "course_registration"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime_minutes: 30

cache:
  type: "redis"
  host: "redis" # docker-compose service name
  port: 6380
  password: ""
  db: 0
  max_retries: 3
  pool_size: 10
  pool_timeout: 30
  idle_timeout: 300
  ttl_minutes: 60

queue:
  type: "memory"
  buffer_size: 1000
  worker_count: 10
  retry_attempts: 3

registration:
  max_courses_per_student: 6
  waitlist_max_size: 50
  registration_timeout_minutes: 5
  concurrent_registrations_limit: 100

log:
  level: "info"
  format: "json"
  output: "stdout"
