# Production Configuration
app:
  name: "course-registration-system"
  version: "1.0.0"
  environment: "production"
  description: "University Course Registration System"

server:
  host: "0.0.0.0"
  port: "8080"
  read_timeout: 30
  write_timeout: 30
  max_header_bytes: 1048576

database:
  driver: "postgres"
  host: "pgbouncer"
  port: 6432
  username: "postgres"
  password: "${DB_PASSWORD}"
  name: "course_registration"
  ssl_mode: "require"
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime_minutes: 60

cache:
  type: "redis"
  host: "redis-master"
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 0
  max_retries: 3
  pool_size: 20
  pool_timeout: 30
  idle_timeout: 300
  ttl_minutes: 60
  sentinel:
    enabled: true
    master_name: "mymaster"
    sentinel_addrs: ["redis-sentinel-1:26379", "redis-sentinel-2:26379", "redis-sentinel-3:26379"]
    sentinel_password: ""

queue:
  type: "redis"
  buffer_size: 2000
  worker_count: 5
  retry_attempts: 3

registration:
  max_courses_per_student: 6
  waitlist_max_size: 100
  registration_timeout_minutes: 5
  concurrent_registrations_limit: 200
  waitlist_repository: "redis"
  waitlist_fallback_enabled: true

log:
  level: "warn"
  format: "json"
  output: "file"
  file_path: "/var/log/course-registration/production.log"
